<?php

namespace BackendBundle\Repository;

/**
 * BatteryTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatteryTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
