<?php

namespace BackendBundle\Repository;

/**
 * EscRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscRepository extends \Doctrine\ORM\EntityRepository
{
}
