<?php

namespace BackendBundle\Repository;

/**
 * GlobalOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class GlobalOrderRepository extends \Doctrine\ORM\EntityRepository
{

	public function hasBasket ($user){
		$qb=$this->createQueryBuilder("b")
			->join("b.user", "u")
			->leftJoin("b.order_details","od")
			->where("b.open = true")
			->andWhere("b.user = :user")
			->setParameter("user", $user)
		;
		$result = $qb->getQuery()->getResult();
		if ($result) return $result[0]; else return false;
	}	

}
