<?php

namespace BackendBundle\Repository;

/**
 * GlobalOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
