<?php

namespace BackendBundle\Repository;

/**
 * MotorTurnsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotorTurnsRepository extends \Doctrine\ORM\EntityRepository
{
}
