<?php

namespace BackendBundle\Repository;

/**
 * Order_detailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Order_detailRepository extends \Doctrine\ORM\EntityRepository
{

	public function isInBasket ($globalOrder,$product){

	$qb=$this->createQueryBuilder("o")		
		->where('o.globalOrder = :globalOrder')
		->setParameter('globalOrder', $globalOrder)
		->andWhere('o.product = :product')
		->setParameter('product', $product)
		;
	;
	$result = $qb->getQuery()->getResult();
	if ($result) return $result[0]; else return false;
	}
}
