<?php

namespace BackendBundle\Repository;

/**
 * Order_detailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Order_detailRepository extends \Doctrine\ORM\EntityRepository
{

	public function isInBasket ($globalOrder,$product){

	$qb=$this->createQueryBuilder("o")		
		->where('o.globalOrder = :globalOrder')
		->setParameter('globalOrder', $globalOrder)
		->andWhere('o.product = :product')
		->setParameter('product', $product)
		;
	;
	$result = $qb->getQuery()->getResult();
	if ($result) return $result[0]; else return false;
	}

	public function deleteOrderDetails($globalOrder){
		$qb = $this->createQueryBuilder('od');
		$qb->delete('Order_detail', 'od');
		$qb->where('od.globalOrder = :globalOrder');
		$qb->setParameter('globalOrder', $globalOrder);
		$query = $qb->getQuery();
    	$result = $query->getResult();

	}

	public function total_global_order($global_order_id){
        
        $qb = $this->createQueryBuilder('o')
            ->select('SUM(p.price * o.quantity)')
            ->join('o.globalOrder', 'g')
            ->join('o.product', 'p')
            ->where ('g.id='.$global_order_id);
        
        $result= $qb->getQuery()->getSingleResult();
        
        //var_dump($result);die;
        return $result;
    }	
}
