<?php

namespace BackendBundle\Repository;

/**
 * PowerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PowerRepository extends \Doctrine\ORM\EntityRepository
{
}
