<?php

namespace BackendBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
	public function getResultResearch($research) {

	$qb = $this->createQueryBuilder('p')	    
	    ->where ('p.lib LIKE :research')
	    ->setParameter('research','%'.$research.'%')
	;

    return $qb->getQuery()->getResult();
	}
}
