<?php

namespace BackendBundle\Repository;

/**
 * ScaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScaleRepository extends \Doctrine\ORM\EntityRepository
{
}
