<?php

namespace BackendBundle\Repository;

/**
 * SecondCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecondCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
