<?php

namespace BackendBundle\Repository;

/**
 * TiresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiresRepository extends \Doctrine\ORM\EntityRepository
{
}
