<?php

namespace BackendBundle\Repository;

/**
 * TiresColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiresColorRepository extends \Doctrine\ORM\EntityRepository
{
}
