<?php

namespace BackendBundle\Repository;

/**
 * VehiculeTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculeTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
