<?php

namespace BackendBundle\Repository;

/**
 * WtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WtRepository extends \Doctrine\ORM\EntityRepository
{
}
